// recipes-v2.js
// NOUVEAU catalogue My Coach Nutrition, reconstruit recette par recette pour
// garantir : cohérence, macros réalistes, allergènes/régimes fiables, couverture
// complète des combinaisons. Construit À CÔTÉ de recipes.js (qui reste actif)
// tant que le catalogue n'est pas complet ; on basculera le require quand prêt.
//
// Schéma par recette :
//   id, nom, type (petit-dejeuner | plat | collation), gout (sucre | sale),
//   cuisines[], regime[] (vegetarien/vegan/sans-porc/sans-gluten...),
//   objectifs[] (perte/maintien/muscle/energie), budget (eco|normal),
//   allergenes[] (gluten/lactose/oeuf/arachide/fruits-a-coque/poisson/
//                 crustaces/soja/sesame),
//   motsCles[], kcal/proteines/glucides/lipides (par portion), tempsMinutes,
//   ingredients[{nom, quantite, unite, rayon}] (POUR 1 PERSONNE), etapes[].

const RECIPES = [
  // ==================== PETITS-DÉJEUNERS ====================
  {
    id: 'pd-porridge-sarrasin-pomme',
    nom: 'Porridge de sarrasin pomme-cannelle',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['fruits-a-coque'],
    motsCles: ['sarrasin', 'pomme', 'cannelle', 'chia', 'proteine de pois', 'lait d amande'],
    kcal: 390, proteines: 23, glucides: 52, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: "Flocons de sarrasin", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Protéine de pois', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Verser les flocons de sarrasin, le lait d'amande et la cannelle dans une petite casserole.",
      'Faire chauffer 5 minutes à feu doux en remuant régulièrement.',
      'Ajouter la protéine de pois hors du feu et mélanger jusqu\'à obtenir une texture crémeuse.',
      'Couper la pomme en petits dés.',
      'Servir le porridge avec les dés de pomme et les graines de chia.',
    ],
  },
  {
    id: 'pd-omelette-epinards-feta',
    nom: 'Omelette moelleuse aux épinards, tomate et feta',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf', 'lactose'],
    motsCles: ['oeufs', 'epinards', 'tomate', 'feta'],
    kcal: 310, proteines: 31, glucides: 6, lipides: 18,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Épinards frais', quantite: 70, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Feta', quantite: 20, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs dans un bol.",
      'Couper la tomate en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les épinards pendant 1 minute.",
      "Verser les œufs battus et cuire à feu doux jusqu'à ce que l'omelette soit prise.",
      'Ajouter la tomate et la feta émiettée avant de plier l\'omelette.',
    ],
  },
  {
    id: 'pd-bowl-skyr-fruits-rouges',
    nom: 'Bowl skyr, fruits rouges et amandes',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['skyr', 'fruits rouges', 'amandes', 'chia', 'miel'],
    kcal: 295, proteines: 27, glucides: 23, lipides: 11,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Skyr nature', quantite: 200, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Fruits rouges', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Amandes', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Verser le skyr dans un bol.',
      'Ajouter les fruits rouges sur le dessus.',
      'Concasser légèrement les amandes.',
      'Parsemer avec les amandes et les graines de chia.',
      'Ajouter le miel en filet juste avant de servir.',
    ],
  },
  {
    id: 'pd-tofu-brouille-mediterraneen',
    nom: 'Tofu brouillé méditerranéen aux champignons',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu', 'champignons', 'tomate', 'epinards', 'curcuma'],
    kcal: 314, proteines: 24, glucides: 14, lipides: 18,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Champignons', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émietter le tofu à la fourchette pour obtenir une texture de brouillade.',
      'Couper les champignons et la tomate en petits morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les champignons pendant 3 minutes.",
      'Ajouter le tofu, le curcuma, la tomate et les épinards.',
      "Cuire 5 minutes en mélangeant jusqu'à ce que l'ensemble soit chaud et fondant.",
    ],
  },
  {
    id: 'pd-pancakes-farine-riz-banane',
    nom: 'Pancakes légers à la farine de riz et banane',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['oeuf', 'fruits-a-coque'],
    motsCles: ['farine de riz', 'banane', 'oeuf', 'puree d amande'],
    kcal: 420, proteines: 14, glucides: 64, lipides: 12,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de riz', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Banane', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Lait d'amande", quantite: 100, unite: 'ml', rayon: 'Crèmerie' },
      { nom: "Purée d'amande", quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Écraser la banane dans un bol.',
      "Ajouter l'œuf, le lait d'amande et la purée d'amande, puis mélanger.",
      'Incorporer la farine de riz et la levure chimique.',
      'Faire cuire de petites portions de pâte dans une poêle chaude, 2 minutes par face.',
      'Servir les pancakes encore tièdes.',
    ],
  },
  {
    id: 'pd-tartines-saumon-avocat-oeuf',
    nom: 'Tartines complètes saumon, avocat et œuf',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'poisson', 'oeuf'],
    motsCles: ['pain complet', 'saumon fume', 'avocat', 'oeuf'],
    kcal: 416, proteines: 24, glucides: 35, lipides: 20,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain complet', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Saumon fumé', quantite: 60, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Jus de citron', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Ciboulette', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire l'œuf 6 minutes dans l'eau frémissante, puis l'écaler.",
      "Écraser l'avocat avec le jus de citron.",
      'Griller légèrement les tranches de pain complet.',
      "Étaler l'avocat sur le pain.",
      "Ajouter le saumon fumé, l'œuf coupé en deux et la ciboulette.",
    ],
  },
  {
    id: 'pd-chia-pudding-coco-mangue',
    nom: 'Chia pudding coco, mangue et citron vert',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: [],
    motsCles: ['chia', 'lait de coco', 'yaourt vegetal', 'mangue'],
    kcal: 339, proteines: 12, glucides: 30, lipides: 19,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Graines de chia', quantite: 30, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de coco', quantite: 120, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Yaourt végétal nature', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Mangue', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Jus de citron vert', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Mélanger les graines de chia avec le lait de coco et le yaourt végétal.',
      'Laisser épaissir au réfrigérateur au moins 30 minutes.',
      'Couper la mangue en petits dés.',
      'Ajouter le jus de citron vert dans le pudding.',
      'Servir avec les dés de mangue sur le dessus.',
    ],
  },
  {
    id: 'pd-galette-pois-chiches-socca',
    nom: 'Galette de pois chiches façon socca et tomates fraîches',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf'],
    motsCles: ['pois chiches', 'socca', 'tomates cerises', 'roquette'],
    kcal: 326, proteines: 25, glucides: 34, lipides: 10,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de pois chiches', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomates cerises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine de pois chiches avec 100 ml d'eau et les blancs d'œufs.",
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Verser la pâte et cuire la galette 3 minutes par face.',
      'Couper les tomates cerises en deux.',
      'Servir la galette avec la roquette et les tomates fraîches.',
    ],
  },
  {
    id: 'pd-overnight-oats-poire-cacao',
    nom: 'Overnight oats poire, cacao et skyr',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['avoine sans gluten', 'skyr', 'poire', 'cacao'],
    kcal: 384, proteines: 25, glucides: 62, lipides: 4,
    tempsMinutes: 5,
    ingredients: [
      { nom: "Flocons d'avoine certifiés sans gluten", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Skyr nature', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Poire', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Cacao non sucré', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 50, unite: 'ml', rayon: 'Crèmerie' },
    ],
    etapes: [
      "Mélanger les flocons d'avoine, le skyr, le lait d'amande et le cacao.",
      'Couper la poire en petits dés.',
      'Incorporer la moitié de la poire dans la préparation.',
      'Placer au réfrigérateur au moins 2 heures.',
      'Ajouter le reste de poire et le miel au moment de servir.',
    ],
  },
  {
    id: 'pd-burrito-oeufs-haricots-noirs',
    nom: 'Breakfast burrito aux œufs et haricots noirs',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mexicaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf'],
    motsCles: ['tortilla', 'oeufs', 'haricots noirs', 'avocat'],
    kcal: 523, proteines: 24, glucides: 55, lipides: 23,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tortilla de blé', quantite: 1, unite: 'pièce', rayon: 'Boulangerie' },
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Haricots noirs cuits', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Salsa', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Battre les œufs dans un bol.',
      'Faire cuire les œufs brouillés dans une poêle chaude.',
      'Réchauffer les haricots noirs pendant 2 minutes.',
      'Garnir la tortilla avec les œufs, les haricots, l\'avocat, la tomate et la salsa.',
      'Rouler fermement le burrito avant de servir.',
    ],
  },
  {
    id: 'pd-bowl-soja-kiwi-chanvre',
    nom: 'Bowl protéiné soja, kiwi et graines de chanvre',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['yaourt de soja', 'proteine de pois', 'kiwi', 'chia', 'chanvre'],
    kcal: 386, proteines: 31, glucides: 34, lipides: 14,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Yaourt de soja nature', quantite: 160, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Kiwi', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Flocons d'avoine certifiés sans gluten", quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chanvre', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger le yaourt de soja avec la protéine de pois jusqu\'à obtenir une texture lisse.',
      'Couper le kiwi en petits morceaux.',
      'Verser la préparation dans un bol.',
      'Ajouter les flocons d\'avoine, les graines de chia et les graines de chanvre.',
      'Disposer le kiwi sur le dessus et servir frais.',
    ],
  },
  {
    id: 'pd-brouillade-tofu-courgette-poivron',
    nom: 'Brouillade de tofu au curcuma, courgette et poivron',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu', 'courgette', 'poivron', 'epinards', 'curcuma'],
    kcal: 371, proteines: 28, glucides: 17, lipides: 21,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Courgette', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Poivron rouge', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Graines de courge', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émietter le tofu à la fourchette.',
      'Couper la courgette et le poivron en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Ajouter la courgette, le poivron, les épinards, le tofu et le curcuma.',
      'Cuire 6 minutes en remuant, puis terminer avec les graines de courge.',
    ],
  },
  {
    id: 'pd-pancakes-vegan-sarrasin-myrtilles',
    nom: 'Pancakes vegan sarrasin, myrtilles et vanille',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['sarrasin', 'proteine de soja', 'myrtilles', 'compote'],
    kcal: 411, proteines: 27, glucides: 60, lipides: 7,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de sarrasin', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Protéine de soja', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 120, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Compote de pomme sans sucres ajoutés', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Myrtilles', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger la farine de sarrasin, la protéine de soja et la levure chimique.',
      'Ajouter le lait de soja et la compote de pomme.',
      'Mélanger jusqu\'à obtenir une pâte épaisse.',
      'Faire cuire de petits pancakes dans une poêle chaude, 2 minutes par face.',
      'Servir avec les myrtilles sur le dessus.',
    ],
  },
  {
    id: 'pd-tartines-tempeh-avocat',
    nom: 'Tartines sans gluten au tempeh doré et avocat',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['soja', 'sesame'],
    motsCles: ['pain sans gluten', 'tempeh', 'avocat', 'tomate', 'sesame'],
    kcal: 455, proteines: 23, glucides: 48, lipides: 19,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain sans gluten', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Tempeh nature', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Graines de sésame', quantite: 5, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Jus de citron', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tempeh en fines lamelles.',
      'Faire dorer le tempeh 3 minutes dans une poêle chaude.',
      "Écraser l'avocat avec le jus de citron.",
      'Griller les tranches de pain sans gluten.',
      "Garnir avec l'avocat, la tomate, le tempeh et les graines de sésame.",
    ],
  },
  {
    id: 'pd-pudding-chia-cacao-fraise-soja',
    nom: 'Pudding chia cacao, fraise et soja protéiné',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja', 'fruits-a-coque'],
    motsCles: ['chia', 'lait de soja', 'proteine de pois', 'cacao', 'fraises', 'cajou'],
    kcal: 360, proteines: 29, glucides: 25, lipides: 16,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Graines de chia', quantite: 25, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cacao non sucré', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Fraises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Purée de cajou', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger les graines de chia, le lait de soja, la protéine de pois et le cacao.',
      'Laisser épaissir au réfrigérateur au moins 30 minutes.',
      'Couper les fraises en morceaux.',
      'Mélanger à nouveau le pudding pour lisser la texture.',
      'Ajouter les fraises et la purée de cajou au moment de servir.',
    ],
  },
  {
    id: 'pd-crepe-pois-chiches-tofu-soyeux',
    nom: 'Crêpe de pois chiches aux champignons et tofu soyeux',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['indienne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['pois chiches', 'tofu soyeux', 'champignons', 'roquette', 'curry'],
    kcal: 337, proteines: 21, glucides: 34, lipides: 13,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de pois chiches', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tofu soyeux', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Champignons', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Curry doux', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine de pois chiches avec 100 ml d'eau et le curry doux.",
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Verser la pâte et cuire la crêpe 3 minutes par face.',
      'Faire revenir les champignons 3 minutes dans la même poêle.',
      'Garnir la crêpe avec le tofu soyeux, les champignons et la roquette.',
    ],
  },
  {
    id: 'pd-bowl-quinoa-edamame-tofu-fume',
    nom: 'Bowl asiatique quinoa, edamame et tofu fumé',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['asiatique'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['quinoa', 'edamame', 'tofu fume', 'concombre', 'tamari'],
    kcal: 444, proteines: 26, glucides: 40, lipides: 20,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Quinoa cuit', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Edamame', quantite: 80, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Tofu fumé', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Concombre', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Avocat', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Déposer le quinoa cuit dans un bol.',
      'Couper le tofu fumé, le concombre et l\'avocat en morceaux.',
      'Ajouter les edamame sur le quinoa.',
      'Disposer le tofu fumé, le concombre et l\'avocat.',
      'Assaisonner avec la sauce tamari sans gluten.',
    ],
  },
  {
    id: 'pd-muffins-sales-saumon-epinards',
    nom: 'Muffins salés saumon, épinards et farine de riz',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf', 'poisson'],
    motsCles: ['saumon fume', 'epinards', 'farine de riz', 'oeufs'],
    kcal: 347, proteines: 35, glucides: 18, lipides: 15,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Saumon fumé', quantite: 50, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Épinards frais', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Farine de riz', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs.",
      'Ajouter la farine de riz et la levure chimique.',
      'Couper le saumon fumé en petits morceaux.',
      'Incorporer le saumon et les épinards à la préparation.',
      'Verser dans deux petits moules et cuire 12 minutes au four.',
    ],
  },
  {
    id: 'pd-porridge-millet-poire-soja',
    nom: 'Porridge de millet, poire et lait de soja',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['millet', 'lait de soja', 'proteine de pois', 'poire', 'lin'],
    kcal: 446, proteines: 31, glucides: 58, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Flocons de millet', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poire', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Graines de lin moulues', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faire chauffer les flocons de millet avec le lait de soja et la cannelle.',
      'Remuer 5 minutes à feu doux jusqu\'à obtenir une texture crémeuse.',
      'Ajouter la protéine de pois hors du feu.',
      'Couper la poire en petits dés.',
      'Servir avec la poire et les graines de lin moulues.',
    ],
  },
  {
    id: 'pd-frittata-dinde-pdt-epinards',
    nom: 'Frittata légère dinde, pomme de terre et épinards',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['italienne'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf'],
    motsCles: ['oeufs', 'dinde', 'pomme de terre', 'epinards'],
    kcal: 381, proteines: 40, glucides: 17, lipides: 17,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Pomme de terre cuite', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Blanc de dinde', quantite: 60, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Épinards frais', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs.",
      'Couper la pomme de terre cuite et le blanc de dinde en petits morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Ajouter les épinards, la pomme de terre et le blanc de dinde.',
      "Verser les œufs battus et cuire à feu doux jusqu'à ce que la frittata soit prise.",
    ],
  },
  {
    id: 'pd-pain-perdu-proteine',
    nom: 'Pain perdu protéiné à la vanille et aux fruits rouges',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'muscle', 'plaisir'],
    budget: 'eco',
    allergenes: ['gluten', 'oeuf', 'lactose'],
    motsCles: ['pain complet', 'oeuf', 'fruits rouges', 'vanille'],
    kcal: 391, proteines: 29, glucides: 53, lipides: 7,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain complet', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: 80, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Fruits rouges', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Vanille', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre l'œuf, les blancs d'œufs, le lait demi-écrémé et la vanille dans une assiette creuse.",
      'Tremper les tranches de pain complet dans le mélange, 30 secondes de chaque côté.',
      'Faire cuire les tranches dans une poêle chaude, 2 minutes par face.',
      'Ajouter les fruits rouges sur le pain perdu.',
      'Terminer avec le miel en filet.',
    ],
  },
  {
    id: 'pd-gaufres-cottage-avoine',
    nom: 'Gaufres cottage cheese, avoine et framboises',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['lactose', 'oeuf', 'gluten'],
    motsCles: ['cottage cheese', 'avoine', 'framboises', 'gaufre'],
    kcal: 352, proteines: 24, glucides: 43, lipides: 8,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Cottage cheese', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Flocons d'avoine", quantite: 40, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Framboises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Sirop d'érable", quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mixer le cottage cheese, l'œuf, les flocons d'avoine et la levure chimique.",
      'Verser la pâte dans un gaufrier chaud.',
      'Cuire 4 à 5 minutes jusqu\'à obtenir une gaufre dorée.',
      'Déposer les framboises sur la gaufre.',
      'Ajouter le sirop d\'érable juste avant de servir.',
    ],
  },
  {
    id: 'pd-riz-au-lait-pomme',
    nom: 'Riz au lait léger cannelle et compotée de pomme',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['energie', 'plaisir'],
    budget: 'eco',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['riz rond', 'pomme', 'raisins secs', 'cannelle', 'amandes'],
    kcal: 387, proteines: 12, glucides: 65, lipides: 9,
    tempsMinutes: 9,
    ingredients: [
      { nom: 'Riz rond cuit', quantite: 130, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: 160, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Raisins secs', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Amandes', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faire chauffer le riz rond avec le lait demi-écrémé et la cannelle.',
      'Remuer 5 minutes à feu doux jusqu\'à obtenir une texture crémeuse.',
      'Couper la pomme en petits dés.',
      'Ajouter la pomme et les raisins secs dans la casserole pendant 2 minutes.',
      'Servir avec les amandes concassées.',
    ],
  },
  {
    id: 'pd-smoothie-matcha-mangue-tofu',
    nom: 'Smoothie épais matcha, mangue et tofu soyeux',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['asiatique'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu soyeux', 'mangue', 'lait de soja', 'matcha', 'lin'],
    kcal: 383, proteines: 30, glucides: 34, lipides: 15,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Tofu soyeux', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Mangue', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Lait de soja', quantite: 150, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de lin moulues', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Matcha', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mettre le tofu soyeux, la mangue et le lait de soja dans un blender.',
      'Ajouter la protéine de pois, les graines de lin moulues et le matcha.',
      'Mixer jusqu\'à obtenir une texture épaisse et lisse.',
      'Verser dans un grand verre ou un bol.',
      'Servir immédiatement bien frais.',
    ],
  },
  {
    id: 'pd-baghrir-fromage-blanc',
    nom: 'Baghrir express au fromage blanc, miel et pistaches',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['orientale'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'plaisir'],
    budget: 'eco',
    allergenes: ['gluten', 'lactose', 'fruits-a-coque'],
    motsCles: ['semoule', 'fromage blanc', 'miel', 'pistaches', 'baghrir'],
    kcal: 370, proteines: 15, glucides: 58, lipides: 9,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Semoule fine', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Fromage blanc', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Pistaches', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la semoule fine, 80 ml d'eau et la levure chimique jusqu'à obtenir une pâte fluide.",
      'Laisser reposer 5 minutes.',
      'Verser la pâte dans une poêle chaude en formant une crêpe épaisse.',
      'Cuire uniquement sur une face jusqu\'à l\'apparition de petits trous.',
      'Servir avec le fromage blanc, le miel et les pistaches concassées.',
    ],
  },
  {
    id: 'pd-toast-ricotta-orange',
    nom: 'Toast italien ricotta, orange et pistaches',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['italienne'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'plaisir'],
    budget: 'normal',
    allergenes: ['gluten', 'lactose', 'fruits-a-coque'],
    motsCles: ['pain complet', 'ricotta', 'orange', 'pistaches', 'zeste'],
    kcal: 345, proteines: 15, glucides: 40, lipides: 14,
    tempsMinutes: 6,
    ingredients: [
      { nom: 'Pain complet', quantite: 1, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Ricotta', quantite: 90, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Orange', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Pistaches', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
      { nom: "Zeste d'orange", quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Griller légèrement la tranche de pain complet.',
      'Mélanger la ricotta avec le zeste d\'orange.',
      'Étaler la ricotta parfumée sur le pain.',
      'Ajouter les quartiers d\'orange.',
      'Terminer avec les pistaches concassées et le miel.',
    ],
  },
  {
    id: 'pd-banana-bread-skyr-pecan',
    nom: 'Banana bread express au skyr et noix de pécan',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['energie', 'plaisir'],
    budget: 'normal',
    allergenes: ['lactose', 'oeuf', 'gluten', 'fruits-a-coque'],
    motsCles: ['banane', 'skyr', 'farine complète', 'noix de pecan', 'banana bread'],
    kcal: 398, proteines: 23, glucides: 47, lipides: 14,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Banane', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Skyr nature', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Farine complète', quantite: 35, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Noix de pécan', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Écraser la banane dans un bol.',
      "Ajouter l'œuf et le skyr, puis mélanger.",
      'Incorporer la farine complète et la levure chimique.',
      'Verser la pâte dans un petit moule individuel.',
      'Ajouter les noix de pécan concassées et cuire 12 minutes au four.',
    ],
  },
  {
    id: 'pd-shakshuka-pois-chiches',
    nom: 'Shakshuka légère aux œufs et pois chiches',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['orientale'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf'],
    motsCles: ['oeufs', 'tomates', 'pois chiches', 'poivron', 'cumin'],
    kcal: 396, proteines: 32, glucides: 28, lipides: 17,
    tempsMinutes: 14,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomates concassées', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Pois chiches cuits', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poivron rouge', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Cumin', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le poivron rouge en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle avec le cumin.",
      'Ajouter le poivron, les tomates concassées et les pois chiches.',
      'Creuser deux petits espaces, puis ajouter les œufs et les blancs d\'œufs.',
      'Couvrir et cuire jusqu\'à ce que les œufs soient pris.',
    ],
  },
  {
    id: 'pd-english-breakfast-leger',
    nom: 'English breakfast léger aux œufs, haricots et champignons',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['anglaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['oeuf'],
    motsCles: ['oeufs', 'haricots blancs', 'champignons', 'dinde'],
    kcal: 421, proteines: 36, glucides: 31, lipides: 17,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Haricots blancs cuits', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Champignons', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Blanc de dinde', quantite: 50, unite: 'g', rayon: 'Boucherie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper les champignons, la tomate et le blanc de dinde en morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Ajouter les champignons, la tomate, les haricots blancs et le blanc de dinde.',
      'Cuire 5 minutes en remuant régulièrement.',
      'Ajouter les œufs dans la poêle et cuire jusqu\'à ce que les blancs soient pris.',
    ],
  },
  {
    id: 'pd-wrap-houmous-oeuf-crudites',
    nom: 'Wrap matinal houmous, œuf et crudités',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'eco',
    allergenes: ['gluten', 'oeuf', 'sesame'],
    motsCles: ['tortilla', 'houmous', 'oeuf', 'carotte', 'concombre'],
    kcal: 416, proteines: 18, glucides: 48, lipides: 16,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Tortilla de blé', quantite: 1, unite: 'pièce', rayon: 'Boulangerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Houmous', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Carotte râpée', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Concombre', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 30, unite: 'g', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire l'œuf 6 minutes dans l'eau frémissante.",
      'Étaler le houmous sur la tortilla de blé.',
      'Ajouter la carotte râpée, le concombre coupé en bâtonnets et la roquette.',
      "Couper l'œuf en deux et le déposer au centre.",
      'Rouler la tortilla fermement avant de servir.',
    ],
  },
  {
    id: 'pd-bircher-muesli-pomme',
    nom: 'Bircher muesli suisse pomme, skyr et noisettes',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['suisse'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'eco',
    allergenes: ['gluten', 'lactose', 'fruits-a-coque'],
    motsCles: ['avoine', 'skyr', 'pomme', 'noisettes', 'raisins secs', 'bircher'],
    kcal: 455, proteines: 26, glucides: 63, lipides: 11,
    tempsMinutes: 6,
    ingredients: [
      { nom: "Flocons d'avoine", quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Skyr nature', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: 80, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Noisettes', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Raisins secs', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger les flocons d'avoine avec le skyr et le lait demi-écrémé.",
      'Râper la pomme directement dans le mélange.',
      'Incorporer les raisins secs.',
      'Laisser reposer 5 minutes pour obtenir une texture fondante.',
      'Ajouter les noisettes concassées avant de servir.',
    ],
  },
  {
    id: 'pd-acai-bowl-proteine',
    nom: 'Açaï bowl protéiné banane et fruits rouges',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['acai', 'banane', 'fruits rouges', 'proteine de pois', 'lait de soja'],
    kcal: 365, proteines: 24, glucides: 38, lipides: 13,
    tempsMinutes: 5,
    ingredients: [
      { nom: "Purée d'açaï", quantite: 100, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Banane', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Fruits rouges', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 100, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Graines de courge', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mixer la purée d'açaï avec la banane, les fruits rouges et le lait de soja.",
      'Ajouter la protéine de pois.',
      'Mixer à nouveau jusqu\'à obtenir une texture épaisse.',
      'Verser dans un bol.',
      'Ajouter les graines de courge sur le dessus.',
    ],
  },
  {
    id: 'pd-crepes-completes-fromage-blanc',
    nom: 'Crêpes complètes fromage blanc et chocolat noir',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie', 'plaisir'],
    budget: 'eco',
    allergenes: ['gluten', 'oeuf', 'lactose'],
    motsCles: ['farine complète', 'oeuf', 'fromage blanc', 'fraises', 'chocolat'],
    kcal: 410, proteines: 22, glucides: 48, lipides: 14,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine complète', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: 100, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Fromage blanc', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Fraises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Chocolat noir', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine complète, l'œuf et le lait demi-écrémé jusqu'à obtenir une pâte fluide.",
      'Faire cuire deux crêpes fines dans une poêle chaude, 1 minute par face.',
      'Étaler le fromage blanc sur les crêpes.',
      'Couper les fraises en morceaux et les ajouter.',
      'Râper le chocolat noir sur le dessus avant de servir.',
    ],
  },
  {
    id: 'pd-granola-yaourt-grec-pomme',
    nom: 'Granola express au yaourt grec, pomme et cannelle',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie', 'plaisir'],
    budget: 'eco',
    allergenes: ['gluten', 'lactose', 'fruits-a-coque'],
    motsCles: ['avoine', 'yaourt grec', 'pomme', 'amandes', 'cannelle', 'granola'],
    kcal: 380, proteines: 22, glucides: 52, lipides: 8,
    tempsMinutes: 7,
    ingredients: [
      { nom: "Flocons d'avoine", quantite: 35, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Yaourt grec nature', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Amandes', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Faire chauffer les flocons d'avoine dans une poêle sèche pendant 3 minutes avec la cannelle.",
      'Couper la pomme en petits dés.',
      'Verser le yaourt grec dans un bol.',
      "Ajouter les flocons d'avoine tièdes et les dés de pomme.",
      'Terminer avec les amandes concassées et le miel.',
    ],
  },
  {
    id: 'pd-semoule-au-lait-datte',
    nom: "Semoule au lait, fleur d'oranger et datte",
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['orientale'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['energie', 'plaisir'],
    budget: 'eco',
    allergenes: ['gluten', 'lactose', 'fruits-a-coque'],
    motsCles: ['semoule', 'lait', 'datte', 'fleur d oranger', 'amande'],
    kcal: 384, proteines: 14, glucides: 59, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Semoule fine', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Datte', quantite: 20, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Purée d'amande", quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: "Fleur d'oranger", quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Faire chauffer le lait demi-écrémé avec la fleur d'oranger.",
      'Verser la semoule fine en pluie.',
      'Remuer 5 minutes à feu doux jusqu\'à obtenir une texture crémeuse.',
      'Couper la datte en petits morceaux.',
      "Servir avec la datte et la purée d'amande.",
    ],
  },
  {
    id: 'pd-scone-skyr-myrtilles',
    nom: 'Scone léger au skyr et aux myrtilles',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['anglaise'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie', 'plaisir'],
    budget: 'normal',
    allergenes: ['gluten', 'lactose', 'oeuf'],
    motsCles: ['farine complète', 'skyr', 'myrtilles', 'scone'],
    kcal: 380, proteines: 22, glucides: 46, lipides: 12,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Farine complète', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Skyr nature', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Myrtilles', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Beurre', quantite: 5, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger la farine complète et la levure chimique.',
      "Ajouter le skyr, l'œuf et le beurre fondu.",
      'Incorporer délicatement les myrtilles.',
      'Former un petit scone individuel sur une plaque.',
      'Cuire 12 minutes au four jusqu\'à ce que le scone soit doré.',
    ],
  },
  {
    id: 'pd-muffin-anglais-oeuf-avocat',
    nom: 'Muffin anglais œuf, avocat et cheddar',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['anglaise'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf', 'lactose'],
    motsCles: ['muffin anglais', 'oeuf', 'avocat', 'cheddar', 'tomate'],
    kcal: 404, proteines: 24, glucides: 36, lipides: 18,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Muffin anglais complet', quantite: 1, unite: 'pièce', rayon: 'Boulangerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 70, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Avocat', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Cheddar', quantite: 15, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomate', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire l'œuf et les blancs d'œufs dans une poêle chaude.",
      'Couper le muffin anglais complet en deux et le griller légèrement.',
      "Écraser l'avocat à la fourchette.",
      'Garnir le muffin avec l\'avocat, les œufs, la tomate et le cheddar.',
      'Refermer le muffin et servir chaud.',
    ],
  },
  {
    id: 'pd-pain-perdu-sale-dinde',
    nom: 'Pain perdu salé dinde, champignons et parmesan',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf', 'lactose'],
    motsCles: ['pain complet', 'dinde', 'champignons', 'parmesan'],
    kcal: 391, proteines: 39, glucides: 34, lipides: 11,
    tempsMinutes: 11,
    ingredients: [
      { nom: 'Pain complet', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Blanc de dinde', quantite: 50, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Champignons', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Parmesan', quantite: 10, unite: 'g', rayon: 'Crèmerie' },
    ],
    etapes: [
      "Battre l'œuf avec les blancs d'œufs dans une assiette creuse.",
      'Tremper les tranches de pain complet dans le mélange.',
      'Couper les champignons et le blanc de dinde en petits morceaux.',
      'Faire cuire le pain dans une poêle chaude, 2 minutes par face.',
      'Ajouter les champignons, le blanc de dinde et le parmesan râpé avant de servir.',
    ],
  },
  {
    id: 'pd-oeufs-benedicte-saumon',
    nom: 'Œufs bénédicte allégés au saumon et yaourt citronné',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['americaine'],
    regime: ['sans-porc'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf', 'poisson', 'lactose'],
    motsCles: ['pain complet', 'saumon fume', 'yaourt grec', 'epinards', 'oeuf'],
    kcal: 320, proteines: 30, glucides: 19, lipides: 14,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Pain complet', quantite: 1, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Saumon fumé', quantite: 60, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Yaourt grec nature', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Épinards frais', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Jus de citron', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Faire cuire l'œuf 6 minutes dans l'eau frémissante.",
      'Mélanger le yaourt grec avec le jus de citron.',
      'Griller légèrement la tranche de pain complet.',
      'Déposer les épinards frais et le saumon fumé sur le pain.',
      "Ajouter l'œuf coupé en deux et la sauce au yaourt citronné.",
    ],
  },
  {
    id: 'pd-polenta-cremeuse-oeuf',
    nom: 'Polenta crémeuse, œuf et tomates au basilic',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['italienne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf', 'lactose'],
    motsCles: ['polenta', 'oeuf', 'tomate', 'parmesan', 'basilic'],
    kcal: 396, proteines: 25, glucides: 43, lipides: 14,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Polenta', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomate', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Parmesan', quantite: 10, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Basilic frais', quantite: 1, unite: 'poignée', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire la polenta avec de l'eau jusqu'à obtenir une texture crémeuse.",
      "Faire cuire l'œuf et les blancs d'œufs dans une poêle chaude.",
      'Couper la tomate en petits dés.',
      'Verser la polenta dans une assiette creuse.',
      "Ajouter les œufs, la tomate, le parmesan, l'huile d'olive et le basilic.",
    ],
  },

  // ==================== PLATS PRINCIPAUX (déjeuner / dîner) ====================
  {
    id: 'plat-poulet-herbes-quinoa-legumes',
    nom: 'Poulet aux herbes, quinoa et légumes du soleil',
    type: 'plat',
    cuisines: ['francaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: [],
    motsCles: ['poulet', 'quinoa', 'courgette', 'aubergine', 'poivron'],
    kcal: 455, proteines: 39, glucides: 39, lipides: 15,
    tempsMinutes: 22,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 140, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Quinoa cuit', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Aubergine', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Poivron rouge', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 10, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Herbes de Provence', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Couper la courgette, l'aubergine et le poivron rouge en morceaux réguliers.",
      "Faire chauffer la moitié de l'huile d'olive dans une poêle.",
      'Cuire les légumes 10 minutes avec les herbes de Provence.',
      "Faire dorer le filet de poulet avec le reste d'huile d'olive, 5 à 6 minutes par face.",
      'Réchauffer le quinoa cuit à feu doux.',
      'Servir le poulet tranché avec le quinoa et les légumes du soleil.',
    ],
  },
  {
    id: 'plat-boeuf-pdt-haricots-verts',
    nom: 'Bœuf maigre, pommes de terre vapeur et haricots verts',
    type: 'plat',
    cuisines: ['francaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: [],
    motsCles: ['boeuf', 'pomme de terre', 'haricots verts', 'moutarde'],
    kcal: 456, proteines: 36, glucides: 50, lipides: 12,
    tempsMinutes: 25,
    ingredients: [
      { nom: 'Steak haché de bœuf 5 %', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Pomme de terre', quantite: 220, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Haricots verts', quantite: 200, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Moutarde', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
      { nom: 'Persil', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Couper la pomme de terre en morceaux.',
      "Cuire la pomme de terre 15 minutes dans l'eau frémissante.",
      "Cuire les haricots verts 8 minutes dans l'eau frémissante.",
      'Faire cuire le steak haché dans une poêle chaude.',
      "Mélanger l'huile d'olive, la moutarde et le persil.",
      'Servir le bœuf avec les pommes de terre, les haricots verts et la sauce moutarde.',
    ],
  },
  {
    id: 'plat-pates-dinde-tomate-parmesan',
    nom: 'Pâtes complètes à la dinde, tomate et parmesan',
    type: 'plat',
    cuisines: ['italienne'],
    regime: ['sans-porc'],
    objectifs: ['maintien', 'muscle', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'lactose'],
    motsCles: ['pates completes', 'dinde', 'tomate', 'parmesan', 'epinards'],
    kcal: 563, proteines: 47, glucides: 60, lipides: 15,
    tempsMinutes: 18,
    ingredients: [
      { nom: 'Pâtes complètes', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Émincé de dinde', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Sauce tomate', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Épinards frais', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Parmesan', quantite: 20, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Basilic', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Cuire les pâtes complètes selon le temps indiqué.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      "Cuire l'émincé de dinde 6 minutes en remuant régulièrement.",
      'Ajouter la sauce tomate, les épinards frais et le basilic.',
      'Égoutter les pâtes et les mélanger à la sauce.',
      'Servir avec le parmesan râpé.',
    ],
  },
  {
    id: 'plat-saumon-riz-brocoli',
    nom: 'Saumon citronné, riz complet et brocoli croquant',
    type: 'plat',
    cuisines: ['mediterraneenne'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['poisson'],
    motsCles: ['saumon', 'riz complet', 'brocoli', 'carotte', 'citron'],
    kcal: 501, proteines: 33, glucides: 45, lipides: 21,
    tempsMinutes: 20,
    ingredients: [
      { nom: 'Pavé de saumon', quantite: 120, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Riz complet cuit', quantite: 110, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Brocoli', quantite: 180, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Carotte', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Jus de citron', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
      { nom: 'Aneth', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Couper le brocoli en petits bouquets et la carotte en fines rondelles.',
      'Cuire le brocoli et la carotte 8 minutes à la vapeur.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Cuire le pavé de saumon 4 minutes par face.',
      'Réchauffer le riz complet cuit à feu doux.',
      'Servir le saumon avec le riz, les légumes, le jus de citron et l\'aneth.',
    ],
  },
  {
    id: 'plat-bowl-medit-tofu-lentilles',
    nom: 'Bowl méditerranéen tofu, lentilles et quinoa',
    type: 'plat',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['tofu', 'lentilles', 'quinoa', 'courgette', 'paprika'],
    kcal: 492, proteines: 35, glucides: 52, lipides: 16,
    tempsMinutes: 18,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Lentilles vertes cuites', quantite: 130, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Quinoa cuit', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Paprika', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tofu ferme en cubes.',
      'Couper la courgette et la tomate en morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Faire dorer le tofu avec le paprika pendant 5 minutes.',
      'Ajouter la courgette, la tomate, les lentilles vertes cuites et le quinoa cuit.',
      'Mélanger 4 minutes à feu moyen avant de servir.',
    ],
  },
  {
    id: 'plat-wok-tempeh-edamame-riz',
    nom: 'Wok de tempeh, edamame et riz sauce tamari',
    type: 'plat',
    cuisines: ['asiatique'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja', 'sesame'],
    motsCles: ['tempeh', 'edamame', 'riz basmati', 'brocoli', 'tamari'],
    kcal: 520, proteines: 35, glucides: 56, lipides: 16,
    tempsMinutes: 17,
    ingredients: [
      { nom: 'Tempeh nature', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Edamame', quantite: 80, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Riz basmati cuit', quantite: 90, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Brocoli', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Carotte', quantite: 70, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Huile de sésame', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tempeh en cubes.',
      'Couper le brocoli en petits bouquets et la carotte en fines lamelles.',
      "Faire chauffer l'huile de sésame dans un wok.",
      'Faire dorer le tempeh 4 minutes avec les edamame.',
      'Ajouter le brocoli, la carotte, le riz basmati cuit et la sauce tamari sans gluten.',
      'Mélanger 5 minutes à feu vif avant de servir.',
    ],
  },
  {
    id: 'plat-curry-tofu-pois-chiches',
    nom: 'Curry indien tofu, pois chiches et épinards',
    type: 'plat',
    cuisines: ['indienne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['tofu', 'pois chiches', 'riz basmati', 'epinards', 'lait de coco', 'curry'],
    kcal: 534, proteines: 34, glucides: 50, lipides: 22,
    tempsMinutes: 20,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 160, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Pois chiches cuits', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Riz basmati cuit', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Épinards frais', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Lait de coco', quantite: 80, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Curry doux', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tofu ferme en cubes.',
      'Couper la tomate en petits morceaux.',
      'Faire chauffer le lait de coco avec le curry doux dans une casserole.',
      'Ajouter le tofu, les pois chiches cuits, la tomate et les épinards frais.',
      'Laisser mijoter 10 minutes à feu doux.',
      'Servir avec le riz basmati cuit.',
    ],
  },
  {
    id: 'plat-chili-dinde-haricots-rouges',
    nom: 'Chili de dinde, haricots rouges et maïs',
    type: 'plat',
    cuisines: ['mexicaine'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: [],
    motsCles: ['dinde', 'haricots rouges', 'riz complet', 'mais', 'paprika'],
    kcal: 548, proteines: 47, glucides: 62, lipides: 12,
    tempsMinutes: 22,
    ingredients: [
      { nom: 'Dinde hachée 5 %', quantite: 150, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Haricots rouges cuits', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Riz complet cuit', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tomate concassée', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poivron rouge', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Maïs', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Paprika fumé', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le poivron rouge en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle profonde.",
      'Cuire la dinde hachée 5 minutes avec le paprika fumé.',
      'Ajouter la tomate concassée, les haricots rouges, le poivron et le maïs.',
      'Laisser mijoter 10 minutes.',
      'Servir le chili avec le riz complet cuit.',
    ],
  },
  {
    id: 'plat-cobb-bowl-poulet-oeuf',
    nom: 'Cobb bowl léger poulet, œuf et patate douce',
    type: 'plat',
    cuisines: ['americaine'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf'],
    motsCles: ['poulet', 'oeuf', 'patate douce', 'concombre', 'avocat'],
    kcal: 449, proteines: 38, glucides: 36, lipides: 17,
    tempsMinutes: 24,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Patate douce', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Concombre', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Avocat', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper la patate douce en cubes.',
      'Cuire la patate douce 15 minutes à la vapeur.',
      "Faire cuire l'œuf 9 minutes dans l'eau frémissante.",
      "Faire dorer le filet de poulet dans une poêle avec l'huile d'olive.",
      'Couper la tomate, le concombre et l\'avocat en morceaux.',
      "Servir le tout dans un bol avec l'œuf coupé en deux.",
    ],
  },
  {
    id: 'plat-assiette-orientale-oeufs-lentilles',
    nom: 'Assiette orientale œufs, lentilles corail et patate douce',
    type: 'plat',
    cuisines: ['orientale'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf'],
    motsCles: ['oeufs', 'lentilles corail', 'patate douce', 'oignon', 'cumin'],
    kcal: 520, proteines: 34, glucides: 55, lipides: 18,
    tempsMinutes: 24,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 120, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Lentilles corail cuites', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Patate douce', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate concassée', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Oignon', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Cumin', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Couper la patate douce en petits cubes et l'oignon en fines lamelles.",
      'Cuire la patate douce 12 minutes à la vapeur.',
      "Faire chauffer l'huile d'olive dans une poêle avec le cumin.",
      'Ajouter l\'oignon, la tomate concassée, les lentilles corail cuites et la patate douce.',
      'Ajouter les œufs et les blancs d\'œufs au centre de la poêle.',
      'Couvrir et cuire jusqu\'à ce que les œufs soient pris.',
    ],
  },
  {
    id: 'plat-penne-sg-thon-courgette',
    nom: 'Penne sans gluten au thon, courgette et tomate basilic',
    type: 'plat',
    cuisines: ['italienne'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['poisson', 'lactose'],
    motsCles: ['penne sans gluten', 'thon', 'courgette', 'tomate', 'parmesan'],
    kcal: 490, proteines: 39, glucides: 61, lipides: 10,
    tempsMinutes: 18,
    ingredients: [
      { nom: 'Penne de maïs sans gluten', quantite: 65, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Thon au naturel', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce tomate', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Parmesan', quantite: 10, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Basilic', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Cuire les penne de maïs sans gluten selon le temps indiqué.',
      'Couper la courgette en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Cuire la courgette 5 minutes, puis ajouter la sauce tomate et le basilic.',
      "Égoutter le thon et l'ajouter à la sauce.",
      'Mélanger les pâtes avec la sauce et servir avec le parmesan râpé.',
    ],
  },
  {
    id: 'plat-risotto-vegan-champignons',
    nom: 'Risotto vegan aux champignons, haricots blancs et épinards',
    type: 'plat',
    cuisines: ['italienne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['riz arborio', 'champignons', 'haricots blancs', 'epinards', 'creme de soja', 'risotto'],
    kcal: 526, proteines: 25, glucides: 76, lipides: 14,
    tempsMinutes: 24,
    ingredients: [
      { nom: 'Riz arborio', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Haricots blancs cuits', quantite: 120, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Champignons', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Crème de soja', quantite: 50, unite: 'ml', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Persil', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Couper les champignons en lamelles.',
      "Faire chauffer l'huile d'olive dans une casserole.",
      'Ajouter le riz arborio et les champignons, puis remuer 2 minutes.',
      "Ajouter progressivement de l'eau chaude jusqu'à ce que le riz soit fondant.",
      'Incorporer les haricots blancs, les épinards frais et la crème de soja.',
      'Laisser épaissir 3 minutes, puis terminer avec le persil.',
    ],
  },
  {
    id: 'plat-crevettes-sicilienne-polenta',
    nom: 'Crevettes à la sicilienne, polenta et fenouil',
    type: 'plat',
    cuisines: ['italienne'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['crustaces'],
    motsCles: ['crevettes', 'polenta', 'fenouil', 'tomates cerises', 'olives'],
    kcal: 505, proteines: 43, glucides: 60, lipides: 11,
    tempsMinutes: 20,
    ingredients: [
      { nom: 'Crevettes décortiquées', quantite: 150, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Polenta', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Fenouil', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomates cerises', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Olives noires', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Câpres', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Cuire la polenta dans de l'eau chaude en remuant jusqu'à obtenir une texture crémeuse.",
      'Émincer le fenouil et couper les tomates cerises en deux.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Cuire le fenouil 5 minutes, puis ajouter les crevettes.',
      'Ajouter les tomates cerises, les olives noires et les câpres.',
      'Servir les crevettes et les légumes sur la polenta crémeuse.',
    ],
  },
  {
    id: 'plat-pad-thai-vegan-tofu',
    nom: 'Pad thaï vegan tofu, nouilles de riz et cacahuète',
    type: 'plat',
    cuisines: ['asiatique'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['soja', 'arachide', 'sesame'],
    motsCles: ['tofu', 'nouilles de riz', 'chou chinois', 'cacahuetes', 'tamari', 'pad thai'],
    kcal: 580, proteines: 32, glucides: 64, lipides: 22,
    tempsMinutes: 20,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 160, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Nouilles de riz', quantite: 55, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Chou chinois', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Carotte', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Pousses de soja', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Cacahuètes', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Huile de sésame', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les nouilles de riz selon le temps indiqué.',
      'Couper le tofu en cubes, la carotte en fines lamelles et le chou chinois en lanières.',
      "Faire chauffer l'huile de sésame dans un wok.",
      'Faire dorer le tofu 5 minutes.',
      'Ajouter la carotte, le chou chinois, les pousses de soja, les nouilles et la sauce tamari sans gluten.',
      'Mélanger 3 minutes à feu vif, puis servir avec les cacahuètes concassées.',
    ],
  },
  {
    id: 'plat-poulet-teriyaki-pak-choi',
    nom: 'Poulet teriyaki léger, riz jasmin et pak choï',
    type: 'plat',
    cuisines: ['asiatique'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['sesame', 'soja'],
    motsCles: ['poulet', 'riz jasmin', 'pak choi', 'carotte', 'teriyaki', 'tamari'],
    kcal: 470, proteines: 37, glucides: 55, lipides: 11,
    tempsMinutes: 18,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 140, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Riz jasmin cuit', quantite: 130, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Pak choï', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Carotte', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Huile de sésame', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le filet de poulet en lamelles.',
      'Couper le pak choï et la carotte en morceaux.',
      'Mélanger la sauce tamari sans gluten avec le miel.',
      "Faire chauffer l'huile de sésame dans une poêle.",
      'Cuire le poulet 6 minutes, puis ajouter le pak choï, la carotte et la sauce.',
      'Servir avec le riz jasmin cuit.',
    ],
  },
  {
    id: 'plat-soba-sarrasin-tofu-fume',
    nom: 'Soba 100 % sarrasin, œuf, tofu fumé et concombre',
    type: 'plat',
    cuisines: ['asiatique'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja', 'oeuf', 'sesame'],
    motsCles: ['soba', 'sarrasin', 'tofu fume', 'edamame', 'concombre', 'oeuf'],
    kcal: 510, proteines: 37, glucides: 54, lipides: 16,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Nouilles soba 100 % sarrasin sans gluten', quantite: 65, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tofu fumé', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Edamame', quantite: 50, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Concombre', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
      { nom: 'Graines de sésame', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les nouilles soba 100 % sarrasin sans gluten selon le temps indiqué.',
      "Faire cuire l'œuf 7 minutes dans l'eau frémissante.",
      'Couper le tofu fumé et le concombre en morceaux.',
      "Égoutter les nouilles et les rincer à l'eau froide.",
      'Mélanger les soba avec le tofu fumé, les edamame, le concombre et la sauce tamari sans gluten.',
      "Ajouter l'œuf coupé en deux et les graines de sésame.",
    ],
  },
  {
    id: 'plat-dahl-tofu-lentilles-corail',
    nom: 'Dahl protéiné tofu, lentilles corail et épinards',
    type: 'plat',
    cuisines: ['indienne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['tofu', 'lentilles corail', 'riz basmati', 'epinards', 'lait de coco', 'dahl'],
    kcal: 540, proteines: 36, glucides: 58, lipides: 17,
    tempsMinutes: 22,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Lentilles corail', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Riz basmati cuit', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Épinards frais', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Lait de coco', quantite: 40, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Curry doux', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Rincer les lentilles corail.',
      'Couper le tofu ferme et la tomate en cubes.',
      "Faire cuire les lentilles corail 10 minutes dans une casserole avec de l'eau.",
      'Ajouter le tofu, la tomate, les épinards frais, le lait de coco et le curry doux.',
      'Laisser mijoter 6 minutes à feu doux.',
      'Servir avec le riz basmati cuit.',
    ],
  },
  {
    id: 'plat-burrito-bowl-vegan-tofu',
    nom: 'Burrito bowl vegan tofu, haricots noirs et quinoa',
    type: 'plat',
    cuisines: ['mexicaine'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['tofu', 'haricots noirs', 'quinoa', 'mais', 'avocat', 'salsa'],
    kcal: 480, proteines: 31, glucides: 55, lipides: 14,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 120, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Haricots noirs cuits', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Quinoa cuit', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Maïs', quantite: 40, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tomate', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Laitue', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Avocat', quantite: 30, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Salsa', quantite: 40, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tofu ferme en cubes.',
      'Faire dorer le tofu 5 minutes dans une poêle chaude.',
      "Couper la tomate, la laitue et l'avocat en morceaux.",
      'Déposer le quinoa cuit dans un bol.',
      'Ajouter les haricots noirs, le tofu, le maïs, la tomate, la laitue et l\'avocat.',
      'Terminer avec la salsa avant de servir.',
    ],
  },
  {
    id: 'plat-cabillaud-vapeur-ratatouille',
    nom: 'Cabillaud vapeur, patate douce et ratatouille minute',
    type: 'plat',
    cuisines: ['francaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['poisson'],
    motsCles: ['cabillaud', 'patate douce', 'courgette', 'aubergine', 'ratatouille'],
    kcal: 463, proteines: 39, glucides: 52, lipides: 11,
    tempsMinutes: 24,
    ingredients: [
      { nom: 'Dos de cabillaud', quantite: 160, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Patate douce', quantite: 180, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Courgette', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Aubergine', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 70, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 10, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Herbes de Provence', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper la patate douce en cubes.',
      'Cuire la patate douce 15 minutes à la vapeur.',
      "Couper la courgette, l'aubergine et la tomate en morceaux.",
      "Faire cuire les légumes dans une poêle avec l'huile d'olive et les herbes de Provence.",
      'Cuire le dos de cabillaud 8 minutes à la vapeur.',
      'Servir le cabillaud avec la patate douce et la ratatouille minute.',
    ],
  },
  {
    id: 'plat-kefta-boeuf-boulgour',
    nom: 'Kefta de bœuf maigre, boulgour et sauce menthe',
    type: 'plat',
    cuisines: ['orientale'],
    regime: ['sans-porc'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['gluten', 'lactose'],
    motsCles: ['boeuf', 'boulgour', 'concombre', 'yaourt grec', 'menthe', 'kefta'],
    kcal: 424, proteines: 42, glucides: 37, lipides: 12,
    tempsMinutes: 20,
    ingredients: [
      { nom: 'Bœuf haché 5 %', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Boulgour cuit', quantite: 150, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Concombre', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Yaourt grec nature', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Cumin', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
      { nom: 'Menthe fraîche', quantite: 1, unite: 'poignée', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Mélanger le bœuf haché avec le cumin.',
      'Former de petites keftas avec les mains.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Cuire les keftas 8 minutes en les retournant régulièrement.',
      'Mélanger le yaourt grec avec la menthe fraîche ciselée.',
      'Servir les keftas avec le boulgour cuit, le concombre, la tomate et la sauce menthe.',
    ],
  },
];

module.exports = { RECIPES };
