// recipes-v2.js
// NOUVEAU catalogue My Coach Nutrition, reconstruit recette par recette pour
// garantir : cohérence, macros réalistes, allergènes/régimes fiables, couverture
// complète des combinaisons. Construit À CÔTÉ de recipes.js (qui reste actif)
// tant que le catalogue n'est pas complet ; on basculera le require quand prêt.
//
// Schéma par recette :
//   id, nom, type (petit-dejeuner | plat | collation), gout (sucre | sale),
//   cuisines[], regime[] (vegetarien/vegan/sans-porc/sans-gluten...),
//   objectifs[] (perte/maintien/muscle/energie), budget (eco|normal),
//   allergenes[] (gluten/lactose/oeuf/arachide/fruits-a-coque/poisson/
//                 crustaces/soja/sesame),
//   motsCles[], kcal/proteines/glucides/lipides (par portion), tempsMinutes,
//   ingredients[{nom, quantite, unite, rayon}] (POUR 1 PERSONNE), etapes[].

const RECIPES = [
  // ==================== PETITS-DÉJEUNERS ====================
  {
    id: 'pd-porridge-sarrasin-pomme',
    nom: 'Porridge de sarrasin pomme-cannelle',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['fruits-a-coque'],
    motsCles: ['sarrasin', 'pomme', 'cannelle', 'chia', 'proteine de pois', 'lait d amande'],
    kcal: 390, proteines: 23, glucides: 52, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: "Flocons de sarrasin", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Protéine de pois', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Verser les flocons de sarrasin, le lait d'amande et la cannelle dans une petite casserole.",
      'Faire chauffer 5 minutes à feu doux en remuant régulièrement.',
      'Ajouter la protéine de pois hors du feu et mélanger jusqu\'à obtenir une texture crémeuse.',
      'Couper la pomme en petits dés.',
      'Servir le porridge avec les dés de pomme et les graines de chia.',
    ],
  },
  {
    id: 'pd-omelette-epinards-feta',
    nom: 'Omelette moelleuse aux épinards, tomate et feta',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf', 'lactose'],
    motsCles: ['oeufs', 'epinards', 'tomate', 'feta'],
    kcal: 310, proteines: 31, glucides: 6, lipides: 18,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Épinards frais', quantite: 70, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Feta', quantite: 20, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs dans un bol.",
      'Couper la tomate en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les épinards pendant 1 minute.",
      "Verser les œufs battus et cuire à feu doux jusqu'à ce que l'omelette soit prise.",
      'Ajouter la tomate et la feta émiettée avant de plier l\'omelette.',
    ],
  },
  {
    id: 'pd-bowl-skyr-fruits-rouges',
    nom: 'Bowl skyr, fruits rouges et amandes',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['skyr', 'fruits rouges', 'amandes', 'chia', 'miel'],
    kcal: 295, proteines: 27, glucides: 23, lipides: 11,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Skyr nature', quantite: 200, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Fruits rouges', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Amandes', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Verser le skyr dans un bol.',
      'Ajouter les fruits rouges sur le dessus.',
      'Concasser légèrement les amandes.',
      'Parsemer avec les amandes et les graines de chia.',
      'Ajouter le miel en filet juste avant de servir.',
    ],
  },
  {
    id: 'pd-tofu-brouille-mediterraneen',
    nom: 'Tofu brouillé méditerranéen aux champignons',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu', 'champignons', 'tomate', 'epinards', 'curcuma'],
    kcal: 314, proteines: 24, glucides: 14, lipides: 18,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Champignons', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émietter le tofu à la fourchette pour obtenir une texture de brouillade.',
      'Couper les champignons et la tomate en petits morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les champignons pendant 3 minutes.",
      'Ajouter le tofu, le curcuma, la tomate et les épinards.',
      "Cuire 5 minutes en mélangeant jusqu'à ce que l'ensemble soit chaud et fondant.",
    ],
  },
  {
    id: 'pd-pancakes-farine-riz-banane',
    nom: 'Pancakes légers à la farine de riz et banane',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['oeuf', 'fruits-a-coque'],
    motsCles: ['farine de riz', 'banane', 'oeuf', 'puree d amande'],
    kcal: 420, proteines: 14, glucides: 64, lipides: 12,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de riz', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Banane', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Lait d'amande", quantite: 100, unite: 'ml', rayon: 'Crèmerie' },
      { nom: "Purée d'amande", quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Écraser la banane dans un bol.',
      "Ajouter l'œuf, le lait d'amande et la purée d'amande, puis mélanger.",
      'Incorporer la farine de riz et la levure chimique.',
      'Faire cuire de petites portions de pâte dans une poêle chaude, 2 minutes par face.',
      'Servir les pancakes encore tièdes.',
    ],
  },
  {
    id: 'pd-tartines-saumon-avocat-oeuf',
    nom: 'Tartines complètes saumon, avocat et œuf',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'poisson', 'oeuf'],
    motsCles: ['pain complet', 'saumon fume', 'avocat', 'oeuf'],
    kcal: 416, proteines: 24, glucides: 35, lipides: 20,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain complet', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Saumon fumé', quantite: 60, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Jus de citron', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Ciboulette', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire l'œuf 6 minutes dans l'eau frémissante, puis l'écaler.",
      "Écraser l'avocat avec le jus de citron.",
      'Griller légèrement les tranches de pain complet.',
      "Étaler l'avocat sur le pain.",
      "Ajouter le saumon fumé, l'œuf coupé en deux et la ciboulette.",
    ],
  },
  {
    id: 'pd-chia-pudding-coco-mangue',
    nom: 'Chia pudding coco, mangue et citron vert',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: [],
    motsCles: ['chia', 'lait de coco', 'yaourt vegetal', 'mangue'],
    kcal: 339, proteines: 12, glucides: 30, lipides: 19,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Graines de chia', quantite: 30, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de coco', quantite: 120, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Yaourt végétal nature', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Mangue', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Jus de citron vert', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Mélanger les graines de chia avec le lait de coco et le yaourt végétal.',
      'Laisser épaissir au réfrigérateur au moins 30 minutes.',
      'Couper la mangue en petits dés.',
      'Ajouter le jus de citron vert dans le pudding.',
      'Servir avec les dés de mangue sur le dessus.',
    ],
  },
  {
    id: 'pd-galette-pois-chiches-socca',
    nom: 'Galette de pois chiches façon socca et tomates fraîches',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf'],
    motsCles: ['pois chiches', 'socca', 'tomates cerises', 'roquette'],
    kcal: 326, proteines: 25, glucides: 34, lipides: 10,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de pois chiches', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomates cerises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine de pois chiches avec 100 ml d'eau et les blancs d'œufs.",
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Verser la pâte et cuire la galette 3 minutes par face.',
      'Couper les tomates cerises en deux.',
      'Servir la galette avec la roquette et les tomates fraîches.',
    ],
  },
  {
    id: 'pd-overnight-oats-poire-cacao',
    nom: 'Overnight oats poire, cacao et skyr',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['avoine sans gluten', 'skyr', 'poire', 'cacao'],
    kcal: 384, proteines: 25, glucides: 62, lipides: 4,
    tempsMinutes: 5,
    ingredients: [
      { nom: "Flocons d'avoine certifiés sans gluten", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Skyr nature', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Poire', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Cacao non sucré', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 50, unite: 'ml', rayon: 'Crèmerie' },
    ],
    etapes: [
      "Mélanger les flocons d'avoine, le skyr, le lait d'amande et le cacao.",
      'Couper la poire en petits dés.',
      'Incorporer la moitié de la poire dans la préparation.',
      'Placer au réfrigérateur au moins 2 heures.',
      'Ajouter le reste de poire et le miel au moment de servir.',
    ],
  },
  {
    id: 'pd-burrito-oeufs-haricots-noirs',
    nom: 'Breakfast burrito aux œufs et haricots noirs',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mexicaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf'],
    motsCles: ['tortilla', 'oeufs', 'haricots noirs', 'avocat'],
    kcal: 523, proteines: 24, glucides: 55, lipides: 23,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tortilla de blé', quantite: 1, unite: 'pièce', rayon: 'Boulangerie' },
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Haricots noirs cuits', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Salsa', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Battre les œufs dans un bol.',
      'Faire cuire les œufs brouillés dans une poêle chaude.',
      'Réchauffer les haricots noirs pendant 2 minutes.',
      'Garnir la tortilla avec les œufs, les haricots, l\'avocat, la tomate et la salsa.',
      'Rouler fermement le burrito avant de servir.',
    ],
  },
];

module.exports = { RECIPES };
