// recipes-simples.js
// Lot de PLATS SIMPLES (<= 5 ingredients) pour renforcer le positionnement
// "manger facile". Ajoutes au catalogue v2 via recipes-v2.js (concat).
// Schema identique a recipes-v2. kcal = 4*prot + 4*gluc + 9*lip (coherence garantie).
// "Oeufs" ecrit sans ligature pour que le detecteur d'allergenes le repere.

const RECIPES = [
  {
    id: 'plat-simple-poulet-riz-brocoli', nom: 'Poulet, riz et brocoli', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien', 'muscle'],
    budget: 'eco', allergenes: [], motsCles: ['poulet', 'riz', 'brocoli'],
    kcal: 544, proteines: 40, glucides: 60, lipides: 16, tempsMinutes: 20,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 140, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Riz basmati', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Brocoli', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet (environ 12 minutes) et égoutter.',
      "Couper le poulet en morceaux et le saisir 6 à 8 minutes à feu moyen-vif dans l'huile, jusqu'à ce qu'il ne soit plus rosé.",
      'Cuire le brocoli 6 minutes à la vapeur ou à l\'eau bouillante. Servir le tout ensemble.',
    ],
  },
  {
    id: 'plat-simple-saumon-pdt-haricots', nom: 'Saumon, pommes de terre et haricots verts', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'normal', allergenes: ['poisson'], motsCles: ['saumon', 'pomme de terre', 'haricots verts'],
    kcal: 468, proteines: 32, glucides: 40, lipides: 20, tempsMinutes: 25,
    ingredients: [
      { nom: 'Pavé de saumon', quantite: 130, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Pommes de terre', quantite: 200, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Haricots verts', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les pommes de terre en morceaux 15 à 18 minutes à l\'eau bouillante salée.',
      "Saisir le saumon 3 à 4 minutes par face dans l'huile, à feu moyen.",
      'Cuire les haricots verts 8 minutes. Dresser le tout dans l\'assiette.',
    ],
  },
  {
    id: 'plat-simple-pates-thon-tomate', nom: 'Pâtes au thon et tomate', type: 'plat', gout: 'sale',
    cuisines: ['italienne'], regime: ['sans-porc'], objectifs: ['maintien', 'energie'],
    budget: 'eco', allergenes: ['gluten', 'poisson'], motsCles: ['pates', 'thon', 'tomate'],
    kcal: 465, proteines: 34, glucides: 62, lipides: 9, tempsMinutes: 15,
    ingredients: [
      { nom: 'Pâtes complètes', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Thon au naturel', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Sauce tomate', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les pâtes selon le paquet (environ 10 minutes) et égoutter.',
      'Chauffer la sauce tomate avec le thon égoutté 5 minutes à feu doux.',
      "Mélanger les pâtes à la sauce, ajouter l'huile et servir.",
    ],
  },
  {
    id: 'plat-simple-omelette-jambon-pdt', nom: 'Omelette au jambon de dinde et pommes de terre', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: ['oeuf'], motsCles: ['oeuf', 'jambon de dinde', 'pomme de terre'],
    kcal: 404, proteines: 28, glucides: 28, lipides: 20, tempsMinutes: 15,
    ingredients: [
      { nom: 'Oeufs', quantite: 3, unite: 'piece', rayon: 'Crèmerie' },
      { nom: 'Jambon de dinde', quantite: 50, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Pommes de terre', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les pommes de terre en dés 12 minutes à l\'eau, puis les poêler 3 minutes.',
      'Battre les oeufs, ajouter le jambon coupé en lanières.',
      "Verser sur les pommes de terre dans la poêle huilée et cuire l'omelette 4 minutes à feu moyen.",
    ],
  },
  {
    id: 'plat-simple-boeuf-semoule-courgette', nom: 'Boeuf haché, semoule et courgette', type: 'plat', gout: 'sale',
    cuisines: ['mediterraneenne'], regime: ['sans-porc'], objectifs: ['maintien', 'muscle'],
    budget: 'eco', allergenes: ['gluten'], motsCles: ['boeuf', 'semoule', 'courgette'],
    kcal: 510, proteines: 32, glucides: 55, lipides: 18, tempsMinutes: 20,
    ingredients: [
      { nom: 'Boeuf haché 5%', quantite: 120, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Semoule', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      "Verser la semoule dans un bol, couvrir d'eau bouillante salée, laisser gonfler 5 minutes.",
      'Poêler le boeuf haché 5 minutes à feu vif.',
      "Ajouter la courgette en dés et l'huile, cuire 5 minutes. Servir sur la semoule.",
    ],
  },
  {
    id: 'plat-simple-tofu-riz-legumes', nom: 'Tofu, riz et poêlée de légumes', type: 'plat', gout: 'sale',
    cuisines: ['asiatique'], regime: ['vegan', 'vegetarien', 'sans-porc'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: ['soja'], motsCles: ['tofu', 'riz', 'legumes'],
    kcal: 436, proteines: 22, glucides: 60, lipides: 12, tempsMinutes: 15,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 150, unite: 'g', rayon: 'Rayon vegetal' },
      { nom: 'Riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poêlée de légumes', quantite: 150, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Sauce soja', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      'Poêler le tofu en dés 5 minutes jusqu\'à coloration.',
      'Ajouter la poêlée de légumes et la sauce soja, cuire 5 minutes. Servir avec le riz.',
    ],
  },
  {
    id: 'plat-simple-dinde-boulgour-poivrons', nom: 'Dinde, boulgour et poivrons', type: 'plat', gout: 'sale',
    cuisines: ['mediterraneenne'], regime: ['sans-porc'], objectifs: ['perte', 'maintien', 'muscle'],
    budget: 'eco', allergenes: ['gluten'], motsCles: ['dinde', 'boulgour', 'poivron'],
    kcal: 497, proteines: 34, glucides: 52, lipides: 17, tempsMinutes: 20,
    ingredients: [
      { nom: 'Escalope de dinde', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Boulgour', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poivron', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le boulgour 10 minutes à l\'eau bouillante salée et égoutter.',
      "Couper la dinde en lanières et la saisir 6 minutes dans l'huile.",
      'Ajouter les poivrons en lamelles, cuire 5 minutes. Servir avec le boulgour.',
    ],
  },
  {
    id: 'plat-simple-cabillaud-riz-epinards', nom: 'Cabillaud, riz et épinards', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'normal', allergenes: ['poisson'], motsCles: ['cabillaud', 'riz', 'epinards'],
    kcal: 504, proteines: 34, glucides: 56, lipides: 16, tempsMinutes: 20,
    ingredients: [
      { nom: 'Dos de cabillaud', quantite: 150, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Épinards frais', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      "Saisir le cabillaud 3 à 4 minutes par face dans l'huile.",
      'Faire tomber les épinards 3 minutes à la poêle. Servir le tout ensemble.',
    ],
  },
  {
    id: 'plat-simple-pates-pesto-poulet', nom: 'Pâtes pesto et poulet', type: 'plat', gout: 'sale',
    cuisines: ['italienne'], regime: ['sans-porc'], objectifs: ['maintien', 'muscle'],
    budget: 'normal', allergenes: ['gluten', 'lactose', 'fruits-a-coque'], motsCles: ['pates', 'pesto', 'poulet'],
    kcal: 572, proteines: 38, glucides: 60, lipides: 20, tempsMinutes: 15,
    ingredients: [
      { nom: 'Pâtes', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Filet de poulet', quantite: 120, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Pesto', quantite: 30, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Parmesan', quantite: 15, unite: 'g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Cuire les pâtes selon le paquet et égoutter.',
      'Couper le poulet en morceaux et le poêler 7 minutes jusqu\'à cuisson complète.',
      'Mélanger les pâtes, le poulet et le pesto. Parsemer de parmesan et servir.',
    ],
  },
  {
    id: 'plat-simple-steak-frites-salade', nom: 'Steak, frites maison et salade', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['maintien', 'muscle'],
    budget: 'normal', allergenes: [], motsCles: ['steak', 'pomme de terre', 'salade'],
    kcal: 488, proteines: 32, glucides: 45, lipides: 20, tempsMinutes: 25,
    ingredients: [
      { nom: 'Steak de boeuf', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Pommes de terre', quantite: 200, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Salade verte', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      "Couper les pommes de terre en frites, les enrober d'huile et cuire 25 minutes au four à 200°C.",
      'Saisir le steak 2 à 3 minutes par face selon la cuisson souhaitée.',
      'Servir avec la salade verte assaisonnée.',
    ],
  },
  {
    id: 'plat-simple-lentilles-riz-tomate', nom: 'Lentilles corail, riz et tomate', type: 'plat', gout: 'sale',
    cuisines: ['indienne'], regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: [], motsCles: ['lentilles', 'riz', 'tomate'],
    kcal: 496, proteines: 18, glucides: 70, lipides: 16, tempsMinutes: 20,
    ingredients: [
      { nom: 'Lentilles corail', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Sauce tomate', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      'Cuire les lentilles corail 12 minutes dans la sauce tomate allongée d\'un peu d\'eau.',
      "Ajouter l'huile, mélanger et servir avec le riz.",
    ],
  },
  {
    id: 'plat-simple-crevettes-riz-courgette', nom: 'Crevettes, riz et courgette', type: 'plat', gout: 'sale',
    cuisines: ['asiatique'], regime: ['sans-porc'], objectifs: ['perte', 'maintien'],
    budget: 'normal', allergenes: ['crustaces', 'soja'], motsCles: ['crevettes', 'riz', 'courgette'],
    kcal: 398, proteines: 28, glucides: 58, lipides: 6, tempsMinutes: 15,
    ingredients: [
      { nom: 'Crevettes', quantite: 120, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce soja', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      'Poêler la courgette en dés 5 minutes, ajouter les crevettes 3 minutes.',
      'Déglacer à la sauce soja et servir avec le riz.',
    ],
  },
  {
    id: 'plat-simple-poulet-patate-douce-haricots', nom: 'Poulet, patate douce et haricots verts', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien', 'muscle'],
    budget: 'eco', allergenes: [], motsCles: ['poulet', 'patate douce', 'haricots verts'],
    kcal: 488, proteines: 36, glucides: 50, lipides: 16, tempsMinutes: 25,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Patate douce', quantite: 200, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Haricots verts', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire la patate douce en cubes 15 minutes à l\'eau ou à la vapeur.',
      "Saisir le poulet 7 minutes dans l'huile jusqu'à cuisson complète.",
      'Cuire les haricots verts 8 minutes. Servir le tout ensemble.',
    ],
  },
  {
    id: 'plat-simple-jambon-pates-petits-pois', nom: 'Pâtes, jambon de dinde et petits pois', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc'], objectifs: ['maintien', 'energie'],
    budget: 'eco', allergenes: ['gluten', 'lactose'], motsCles: ['pates', 'jambon de dinde', 'petits pois'],
    kcal: 466, proteines: 30, glucides: 64, lipides: 10, tempsMinutes: 15,
    ingredients: [
      { nom: 'Pâtes', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Jambon de dinde', quantite: 70, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Petits pois', quantite: 100, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Crème légère', quantite: 30, unite: 'g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Cuire les pâtes et les petits pois ensemble selon le paquet, puis égoutter.',
      'Ajouter le jambon coupé en dés et la crème, réchauffer 2 minutes.',
      'Mélanger et servir.',
    ],
  },
  {
    id: 'plat-simple-riz-cantonais', nom: 'Riz cantonais simplifié', type: 'plat', gout: 'sale',
    cuisines: ['asiatique'], regime: ['sans-porc'], objectifs: ['maintien', 'energie'],
    budget: 'eco', allergenes: ['oeuf', 'soja'], motsCles: ['riz', 'oeuf', 'petits pois', 'jambon de dinde'],
    kcal: 464, proteines: 24, glucides: 65, lipides: 12, tempsMinutes: 15,
    ingredients: [
      { nom: 'Riz', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Oeufs', quantite: 2, unite: 'piece', rayon: 'Crèmerie' },
      { nom: 'Petits pois', quantite: 80, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Jambon de dinde', quantite: 40, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Sauce soja', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz et les petits pois, puis égoutter.',
      'Brouiller les oeufs à la poêle, ajouter le jambon en dés.',
      'Ajouter le riz, les petits pois et la sauce soja, sauter 3 minutes et servir.',
    ],
  },
  {
    id: 'plat-simple-saumon-pates-epinards', nom: 'Pâtes au saumon et épinards', type: 'plat', gout: 'sale',
    cuisines: ['italienne'], regime: ['sans-porc'], objectifs: ['maintien', 'muscle'],
    budget: 'normal', allergenes: ['gluten', 'poisson'], motsCles: ['pates', 'saumon', 'epinards'],
    kcal: 538, proteines: 34, glucides: 60, lipides: 18, tempsMinutes: 15,
    ingredients: [
      { nom: 'Pâtes', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Pavé de saumon', quantite: 120, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Épinards frais', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les pâtes selon le paquet et égoutter.',
      "Cuire le saumon 4 minutes à la poêle dans l'huile, puis l'émietter.",
      'Faire tomber les épinards 3 minutes, mélanger aux pâtes et au saumon. Servir.',
    ],
  },
  {
    id: 'plat-simple-thon-semoule-tomate', nom: 'Thon, semoule et tomate', type: 'plat', gout: 'sale',
    cuisines: ['mediterraneenne'], regime: ['sans-porc'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: ['gluten', 'poisson'], motsCles: ['thon', 'semoule', 'tomate'],
    kcal: 471, proteines: 32, glucides: 52, lipides: 15, tempsMinutes: 15,
    ingredients: [
      { nom: 'Thon au naturel', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Semoule', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tomate', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      "Verser la semoule dans un bol, couvrir d'eau bouillante salée, laisser gonfler 5 minutes.",
      'Couper les tomates en dés, égoutter le thon.',
      "Mélanger semoule, thon, tomates et huile. Servir tiède ou froid.",
    ],
  },
  {
    id: 'plat-simple-pois-chiches-riz-curry', nom: 'Curry de pois chiches au riz', type: 'plat', gout: 'sale',
    cuisines: ['indienne'], regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'], objectifs: ['maintien', 'energie'],
    budget: 'eco', allergenes: [], motsCles: ['pois chiches', 'riz', 'tomate', 'curry'],
    kcal: 480, proteines: 16, glucides: 68, lipides: 16, tempsMinutes: 15,
    ingredients: [
      { nom: 'Pois chiches cuits', quantite: 150, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: 60, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Sauce tomate', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      "Chauffer la sauce tomate avec les pois chiches et l'huile 8 minutes à feu doux.",
      'Servir le curry sur le riz.',
    ],
  },
  {
    id: 'plat-simple-dinde-riz-brocoli', nom: 'Dinde, riz et brocoli', type: 'plat', gout: 'sale',
    cuisines: ['asiatique'], regime: ['sans-porc'], objectifs: ['perte', 'maintien', 'muscle'],
    budget: 'eco', allergenes: ['soja'], motsCles: ['dinde', 'riz', 'brocoli'],
    kcal: 436, proteines: 36, glucides: 55, lipides: 8, tempsMinutes: 20,
    ingredients: [
      { nom: 'Escalope de dinde', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Brocoli', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce soja', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      'Saisir la dinde en lanières 6 minutes à la poêle.',
      'Ajouter le brocoli et la sauce soja, cuire 5 minutes. Servir avec le riz.',
    ],
  },
  {
    id: 'plat-simple-boeuf-riz-poivrons', nom: 'Boeuf, riz et poivrons', type: 'plat', gout: 'sale',
    cuisines: ['mexicaine'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['maintien', 'muscle'],
    budget: 'eco', allergenes: [], motsCles: ['boeuf', 'riz', 'poivron'],
    kcal: 490, proteines: 30, glucides: 52, lipides: 18, tempsMinutes: 20,
    ingredients: [
      { nom: 'Boeuf haché 5%', quantite: 120, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poivron', quantite: 150, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire le riz selon le paquet et égoutter.',
      'Poêler le boeuf haché 5 minutes à feu vif.',
      'Ajouter les poivrons en lamelles, cuire 5 minutes. Servir avec le riz.',
    ],
  },
  {
    id: 'plat-simple-cabillaud-pdt-courgette', nom: 'Cabillaud, pommes de terre et courgette', type: 'plat', gout: 'sale',
    cuisines: ['francaise'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'normal', allergenes: ['poisson'], motsCles: ['cabillaud', 'pomme de terre', 'courgette'],
    kcal: 444, proteines: 33, glucides: 42, lipides: 16, tempsMinutes: 25,
    ingredients: [
      { nom: 'Dos de cabillaud', quantite: 150, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Pommes de terre', quantite: 200, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Courgette', quantite: 120, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuire les pommes de terre en morceaux 15 minutes à l\'eau.',
      "Saisir le cabillaud 3 à 4 minutes par face dans l'huile.",
      'Poêler la courgette en dés 6 minutes. Servir le tout ensemble.',
    ],
  },
  {
    id: 'plat-simple-tofu-nouilles-legumes', nom: 'Wok de tofu, nouilles de riz et légumes', type: 'plat', gout: 'sale',
    cuisines: ['asiatique'], regime: ['vegan', 'vegetarien', 'sans-porc'], objectifs: ['maintien', 'energie'],
    budget: 'eco', allergenes: ['soja'], motsCles: ['tofu', 'nouilles de riz', 'legumes'],
    kcal: 444, proteines: 22, glucides: 62, lipides: 12, tempsMinutes: 15,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 150, unite: 'g', rayon: 'Rayon vegetal' },
      { nom: 'Nouilles de riz', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poêlée de légumes', quantite: 150, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Sauce soja', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Réhydrater les nouilles de riz selon le paquet.',
      'Poêler le tofu en dés 5 minutes, ajouter la poêlée de légumes 5 minutes.',
      'Ajouter les nouilles et la sauce soja, sauter 2 minutes et servir.',
    ],
  },
  {
    id: 'plat-simple-poulet-polenta-tomate', nom: 'Poulet, polenta et tomate', type: 'plat', gout: 'sale',
    cuisines: ['italienne'], regime: ['sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: ['lactose'], motsCles: ['poulet', 'polenta', 'tomate'],
    kcal: 432, proteines: 36, glucides: 45, lipides: 12, tempsMinutes: 20,
    ingredients: [
      { nom: 'Filet de poulet', quantite: 130, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Polenta', quantite: 70, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Sauce tomate', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Parmesan', quantite: 15, unite: 'g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Cuire la polenta selon le paquet, incorporer le parmesan.',
      "Couper le poulet en morceaux et le poêler 7 minutes.",
      'Réchauffer la sauce tomate, napper le poulet et servir avec la polenta.',
    ],
  },
  {
    id: 'plat-simple-quinoa-oeuf-legumes', nom: 'Bowl quinoa, oeuf et avocat', type: 'plat', gout: 'sale',
    cuisines: ['vegetale'], regime: ['vegetarien', 'sans-porc', 'sans-gluten'], objectifs: ['perte', 'maintien'],
    budget: 'eco', allergenes: ['oeuf'], motsCles: ['quinoa', 'oeuf', 'avocat', 'tomate'],
    kcal: 412, proteines: 18, glucides: 40, lipides: 20, tempsMinutes: 15,
    ingredients: [
      { nom: 'Quinoa cuit', quantite: 150, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Oeufs', quantite: 2, unite: 'piece', rayon: 'Crèmerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Cuire les oeufs durs 9 minutes, les écaler et les couper en deux.',
      'Disposer le quinoa dans un bol avec la tomate en dés et l\'avocat en lamelles.',
      'Ajouter les oeufs, assaisonner et servir.',
    ],
  },
];

module.exports = { RECIPES };
