// recipes-v2.js
// NOUVEAU catalogue My Coach Nutrition, reconstruit recette par recette pour
// garantir : cohérence, macros réalistes, allergènes/régimes fiables, couverture
// complète des combinaisons. Construit À CÔTÉ de recipes.js (qui reste actif)
// tant que le catalogue n'est pas complet ; on basculera le require quand prêt.
//
// Schéma par recette :
//   id, nom, type (petit-dejeuner | plat | collation), gout (sucre | sale),
//   cuisines[], regime[] (vegetarien/vegan/sans-porc/sans-gluten...),
//   objectifs[] (perte/maintien/muscle/energie), budget (eco|normal),
//   allergenes[] (gluten/lactose/oeuf/arachide/fruits-a-coque/poisson/
//                 crustaces/soja/sesame),
//   motsCles[], kcal/proteines/glucides/lipides (par portion), tempsMinutes,
//   ingredients[{nom, quantite, unite, rayon}] (POUR 1 PERSONNE), etapes[].

const RECIPES = [
  // ==================== PETITS-DÉJEUNERS ====================
  {
    id: 'pd-porridge-sarrasin-pomme',
    nom: 'Porridge de sarrasin pomme-cannelle',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['fruits-a-coque'],
    motsCles: ['sarrasin', 'pomme', 'cannelle', 'chia', 'proteine de pois', 'lait d amande'],
    kcal: 390, proteines: 23, glucides: 52, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: "Flocons de sarrasin", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Protéine de pois', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Verser les flocons de sarrasin, le lait d'amande et la cannelle dans une petite casserole.",
      'Faire chauffer 5 minutes à feu doux en remuant régulièrement.',
      'Ajouter la protéine de pois hors du feu et mélanger jusqu\'à obtenir une texture crémeuse.',
      'Couper la pomme en petits dés.',
      'Servir le porridge avec les dés de pomme et les graines de chia.',
    ],
  },
  {
    id: 'pd-omelette-epinards-feta',
    nom: 'Omelette moelleuse aux épinards, tomate et feta',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf', 'lactose'],
    motsCles: ['oeufs', 'epinards', 'tomate', 'feta'],
    kcal: 310, proteines: 31, glucides: 6, lipides: 18,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Épinards frais', quantite: 70, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Feta', quantite: 20, unite: 'g', rayon: 'Crèmerie' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs dans un bol.",
      'Couper la tomate en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les épinards pendant 1 minute.",
      "Verser les œufs battus et cuire à feu doux jusqu'à ce que l'omelette soit prise.",
      'Ajouter la tomate et la feta émiettée avant de plier l\'omelette.',
    ],
  },
  {
    id: 'pd-bowl-skyr-fruits-rouges',
    nom: 'Bowl skyr, fruits rouges et amandes',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['skyr', 'fruits rouges', 'amandes', 'chia', 'miel'],
    kcal: 295, proteines: 27, glucides: 23, lipides: 11,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Skyr nature', quantite: 200, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Fruits rouges', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Amandes', quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Verser le skyr dans un bol.',
      'Ajouter les fruits rouges sur le dessus.',
      'Concasser légèrement les amandes.',
      'Parsemer avec les amandes et les graines de chia.',
      'Ajouter le miel en filet juste avant de servir.',
    ],
  },
  {
    id: 'pd-tofu-brouille-mediterraneen',
    nom: 'Tofu brouillé méditerranéen aux champignons',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu', 'champignons', 'tomate', 'epinards', 'curcuma'],
    kcal: 314, proteines: 24, glucides: 14, lipides: 18,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Champignons', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émietter le tofu à la fourchette pour obtenir une texture de brouillade.',
      'Couper les champignons et la tomate en petits morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle, puis ajouter les champignons pendant 3 minutes.",
      'Ajouter le tofu, le curcuma, la tomate et les épinards.',
      "Cuire 5 minutes en mélangeant jusqu'à ce que l'ensemble soit chaud et fondant.",
    ],
  },
  {
    id: 'pd-pancakes-farine-riz-banane',
    nom: 'Pancakes légers à la farine de riz et banane',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['oeuf', 'fruits-a-coque'],
    motsCles: ['farine de riz', 'banane', 'oeuf', 'puree d amande'],
    kcal: 420, proteines: 14, glucides: 64, lipides: 12,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de riz', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Banane', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Lait d'amande", quantite: 100, unite: 'ml', rayon: 'Crèmerie' },
      { nom: "Purée d'amande", quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Écraser la banane dans un bol.',
      "Ajouter l'œuf, le lait d'amande et la purée d'amande, puis mélanger.",
      'Incorporer la farine de riz et la levure chimique.',
      'Faire cuire de petites portions de pâte dans une poêle chaude, 2 minutes par face.',
      'Servir les pancakes encore tièdes.',
    ],
  },
  {
    id: 'pd-tartines-saumon-avocat-oeuf',
    nom: 'Tartines complètes saumon, avocat et œuf',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'poisson', 'oeuf'],
    motsCles: ['pain complet', 'saumon fume', 'avocat', 'oeuf'],
    kcal: 416, proteines: 24, glucides: 35, lipides: 20,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain complet', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Saumon fumé', quantite: 60, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Œuf', quantite: 1, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Jus de citron', quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Ciboulette', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      "Faire cuire l'œuf 6 minutes dans l'eau frémissante, puis l'écaler.",
      "Écraser l'avocat avec le jus de citron.",
      'Griller légèrement les tranches de pain complet.',
      "Étaler l'avocat sur le pain.",
      "Ajouter le saumon fumé, l'œuf coupé en deux et la ciboulette.",
    ],
  },
  {
    id: 'pd-chia-pudding-coco-mangue',
    nom: 'Chia pudding coco, mangue et citron vert',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: [],
    motsCles: ['chia', 'lait de coco', 'yaourt vegetal', 'mangue'],
    kcal: 339, proteines: 12, glucides: 30, lipides: 19,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Graines de chia', quantite: 30, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de coco', quantite: 120, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Yaourt végétal nature', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Mangue', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Jus de citron vert', quantite: 1, unite: 'c. à café', rayon: 'Fruits & légumes' },
    ],
    etapes: [
      'Mélanger les graines de chia avec le lait de coco et le yaourt végétal.',
      'Laisser épaissir au réfrigérateur au moins 30 minutes.',
      'Couper la mangue en petits dés.',
      'Ajouter le jus de citron vert dans le pudding.',
      'Servir avec les dés de mangue sur le dessus.',
    ],
  },
  {
    id: 'pd-galette-pois-chiches-socca',
    nom: 'Galette de pois chiches façon socca et tomates fraîches',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['oeuf'],
    motsCles: ['pois chiches', 'socca', 'tomates cerises', 'roquette'],
    kcal: 326, proteines: 25, glucides: 34, lipides: 10,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de pois chiches', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Tomates cerises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine de pois chiches avec 100 ml d'eau et les blancs d'œufs.",
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Verser la pâte et cuire la galette 3 minutes par face.',
      'Couper les tomates cerises en deux.',
      'Servir la galette avec la roquette et les tomates fraîches.',
    ],
  },
  {
    id: 'pd-overnight-oats-poire-cacao',
    nom: 'Overnight oats poire, cacao et skyr',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['lactose', 'fruits-a-coque'],
    motsCles: ['avoine sans gluten', 'skyr', 'poire', 'cacao'],
    kcal: 384, proteines: 25, glucides: 62, lipides: 4,
    tempsMinutes: 5,
    ingredients: [
      { nom: "Flocons d'avoine certifiés sans gluten", quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Skyr nature', quantite: 150, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Poire', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Cacao non sucré', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Miel', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: "Lait d'amande", quantite: 50, unite: 'ml', rayon: 'Crèmerie' },
    ],
    etapes: [
      "Mélanger les flocons d'avoine, le skyr, le lait d'amande et le cacao.",
      'Couper la poire en petits dés.',
      'Incorporer la moitié de la poire dans la préparation.',
      'Placer au réfrigérateur au moins 2 heures.',
      'Ajouter le reste de poire et le miel au moment de servir.',
    ],
  },
  {
    id: 'pd-burrito-oeufs-haricots-noirs',
    nom: 'Breakfast burrito aux œufs et haricots noirs',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mexicaine'],
    regime: ['vegetarien', 'sans-porc'],
    objectifs: ['muscle', 'energie'],
    budget: 'normal',
    allergenes: ['gluten', 'oeuf'],
    motsCles: ['tortilla', 'oeufs', 'haricots noirs', 'avocat'],
    kcal: 523, proteines: 24, glucides: 55, lipides: 23,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tortilla de blé', quantite: 1, unite: 'pièce', rayon: 'Boulangerie' },
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: 'Haricots noirs cuits', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Salsa', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Battre les œufs dans un bol.',
      'Faire cuire les œufs brouillés dans une poêle chaude.',
      'Réchauffer les haricots noirs pendant 2 minutes.',
      'Garnir la tortilla avec les œufs, les haricots, l\'avocat, la tomate et la salsa.',
      'Rouler fermement le burrito avant de servir.',
    ],
  },
  {
    id: 'pd-bowl-soja-kiwi-chanvre',
    nom: 'Bowl protéiné soja, kiwi et graines de chanvre',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['yaourt de soja', 'proteine de pois', 'kiwi', 'chia', 'chanvre'],
    kcal: 386, proteines: 31, glucides: 34, lipides: 14,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Yaourt de soja nature', quantite: 160, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Kiwi', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Flocons d'avoine certifiés sans gluten", quantite: 15, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chia', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Graines de chanvre', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger le yaourt de soja avec la protéine de pois jusqu\'à obtenir une texture lisse.',
      'Couper le kiwi en petits morceaux.',
      'Verser la préparation dans un bol.',
      'Ajouter les flocons d\'avoine, les graines de chia et les graines de chanvre.',
      'Disposer le kiwi sur le dessus et servir frais.',
    ],
  },
  {
    id: 'pd-brouillade-tofu-courgette-poivron',
    nom: 'Brouillade de tofu au curcuma, courgette et poivron',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['tofu', 'courgette', 'poivron', 'epinards', 'curcuma'],
    kcal: 371, proteines: 28, glucides: 17, lipides: 21,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Tofu ferme', quantite: 180, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Courgette', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Poivron rouge', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Épinards frais', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Graines de courge', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émietter le tofu à la fourchette.',
      'Couper la courgette et le poivron en petits dés.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Ajouter la courgette, le poivron, les épinards, le tofu et le curcuma.',
      'Cuire 6 minutes en remuant, puis terminer avec les graines de courge.',
    ],
  },
  {
    id: 'pd-pancakes-vegan-sarrasin-myrtilles',
    nom: 'Pancakes vegan sarrasin, myrtilles et vanille',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['americaine'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['sarrasin', 'proteine de soja', 'myrtilles', 'compote'],
    kcal: 411, proteines: 27, glucides: 60, lipides: 7,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de sarrasin', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Protéine de soja', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 120, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Compote de pomme sans sucres ajoutés', quantite: 80, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Myrtilles', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger la farine de sarrasin, la protéine de soja et la levure chimique.',
      'Ajouter le lait de soja et la compote de pomme.',
      'Mélanger jusqu\'à obtenir une pâte épaisse.',
      'Faire cuire de petits pancakes dans une poêle chaude, 2 minutes par face.',
      'Servir avec les myrtilles sur le dessus.',
    ],
  },
  {
    id: 'pd-tartines-tempeh-avocat',
    nom: 'Tartines sans gluten au tempeh doré et avocat',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['mediterraneenne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['maintien', 'energie'],
    budget: 'normal',
    allergenes: ['soja', 'sesame'],
    motsCles: ['pain sans gluten', 'tempeh', 'avocat', 'tomate', 'sesame'],
    kcal: 455, proteines: 23, glucides: 48, lipides: 19,
    tempsMinutes: 10,
    ingredients: [
      { nom: 'Pain sans gluten', quantite: 2, unite: 'tranche', rayon: 'Boulangerie' },
      { nom: 'Tempeh nature', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Avocat', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Tomate', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Graines de sésame', quantite: 5, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Jus de citron', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Couper le tempeh en fines lamelles.',
      'Faire dorer le tempeh 3 minutes dans une poêle chaude.',
      "Écraser l'avocat avec le jus de citron.",
      'Griller les tranches de pain sans gluten.',
      "Garnir avec l'avocat, la tomate, le tempeh et les graines de sésame.",
    ],
  },
  {
    id: 'pd-pudding-chia-cacao-fraise-soja',
    nom: 'Pudding chia cacao, fraise et soja protéiné',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja', 'fruits-a-coque'],
    motsCles: ['chia', 'lait de soja', 'proteine de pois', 'cacao', 'fraises', 'cajou'],
    kcal: 360, proteines: 29, glucides: 25, lipides: 16,
    tempsMinutes: 5,
    ingredients: [
      { nom: 'Graines de chia', quantite: 25, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cacao non sucré', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Fraises', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Purée de cajou', quantite: 10, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mélanger les graines de chia, le lait de soja, la protéine de pois et le cacao.',
      'Laisser épaissir au réfrigérateur au moins 30 minutes.',
      'Couper les fraises en morceaux.',
      'Mélanger à nouveau le pudding pour lisser la texture.',
      'Ajouter les fraises et la purée de cajou au moment de servir.',
    ],
  },
  {
    id: 'pd-crepe-pois-chiches-tofu-soyeux',
    nom: 'Crêpe de pois chiches aux champignons et tofu soyeux',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['indienne'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'eco',
    allergenes: ['soja'],
    motsCles: ['pois chiches', 'tofu soyeux', 'champignons', 'roquette', 'curry'],
    kcal: 337, proteines: 21, glucides: 34, lipides: 13,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Farine de pois chiches', quantite: 50, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Tofu soyeux', quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Champignons', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Roquette', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
      { nom: 'Curry doux', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      "Mélanger la farine de pois chiches avec 100 ml d'eau et le curry doux.",
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Verser la pâte et cuire la crêpe 3 minutes par face.',
      'Faire revenir les champignons 3 minutes dans la même poêle.',
      'Garnir la crêpe avec le tofu soyeux, les champignons et la roquette.',
    ],
  },
  {
    id: 'pd-bowl-quinoa-edamame-tofu-fume',
    nom: 'Bowl asiatique quinoa, edamame et tofu fumé',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['asiatique'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['quinoa', 'edamame', 'tofu fume', 'concombre', 'tamari'],
    kcal: 444, proteines: 26, glucides: 40, lipides: 20,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Quinoa cuit', quantite: 100, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Edamame', quantite: 80, unite: 'g', rayon: 'Surgelés' },
      { nom: 'Tofu fumé', quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Concombre', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Avocat', quantite: 40, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Sauce tamari sans gluten', quantite: 1, unite: 'c. à soupe', rayon: 'Épicerie' },
    ],
    etapes: [
      'Déposer le quinoa cuit dans un bol.',
      'Couper le tofu fumé, le concombre et l\'avocat en morceaux.',
      'Ajouter les edamame sur le quinoa.',
      'Disposer le tofu fumé, le concombre et l\'avocat.',
      'Assaisonner avec la sauce tamari sans gluten.',
    ],
  },
  {
    id: 'pd-muffins-sales-saumon-epinards',
    nom: 'Muffins salés saumon, épinards et farine de riz',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['francaise'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf', 'poisson'],
    motsCles: ['saumon fume', 'epinards', 'farine de riz', 'oeufs'],
    kcal: 347, proteines: 35, glucides: 18, lipides: 15,
    tempsMinutes: 15,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 80, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Saumon fumé', quantite: 50, unite: 'g', rayon: 'Poissonnerie' },
      { nom: 'Épinards frais', quantite: 60, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Farine de riz', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Levure chimique', quantite: 5, unite: 'g', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs.",
      'Ajouter la farine de riz et la levure chimique.',
      'Couper le saumon fumé en petits morceaux.',
      'Incorporer le saumon et les épinards à la préparation.',
      'Verser dans deux petits moules et cuire 12 minutes au four.',
    ],
  },
  {
    id: 'pd-porridge-millet-poire-soja',
    nom: 'Porridge de millet, poire et lait de soja',
    type: 'petit-dejeuner',
    gout: 'sucre',
    cuisines: ['francaise'],
    regime: ['vegan', 'vegetarien', 'sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'energie'],
    budget: 'normal',
    allergenes: ['soja'],
    motsCles: ['millet', 'lait de soja', 'proteine de pois', 'poire', 'lin'],
    kcal: 446, proteines: 31, glucides: 58, lipides: 10,
    tempsMinutes: 8,
    ingredients: [
      { nom: 'Flocons de millet', quantite: 45, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Lait de soja', quantite: 200, unite: 'ml', rayon: 'Crèmerie' },
      { nom: 'Protéine de pois', quantite: 20, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Poire', quantite: 100, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Graines de lin moulues', quantite: 10, unite: 'g', rayon: 'Épicerie' },
      { nom: 'Cannelle', quantite: 1, unite: 'c. à café', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faire chauffer les flocons de millet avec le lait de soja et la cannelle.',
      'Remuer 5 minutes à feu doux jusqu\'à obtenir une texture crémeuse.',
      'Ajouter la protéine de pois hors du feu.',
      'Couper la poire en petits dés.',
      'Servir avec la poire et les graines de lin moulues.',
    ],
  },
  {
    id: 'pd-frittata-dinde-pdt-epinards',
    nom: 'Frittata légère dinde, pomme de terre et épinards',
    type: 'petit-dejeuner',
    gout: 'sale',
    cuisines: ['italienne'],
    regime: ['sans-porc', 'sans-gluten'],
    objectifs: ['perte', 'maintien'],
    budget: 'normal',
    allergenes: ['oeuf'],
    motsCles: ['oeufs', 'dinde', 'pomme de terre', 'epinards'],
    kcal: 381, proteines: 40, glucides: 17, lipides: 17,
    tempsMinutes: 12,
    ingredients: [
      { nom: 'Œufs', quantite: 2, unite: 'pièce', rayon: 'Crèmerie' },
      { nom: "Blancs d'œufs", quantite: 100, unite: 'g', rayon: 'Crèmerie' },
      { nom: 'Pomme de terre cuite', quantite: 80, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: 'Blanc de dinde', quantite: 60, unite: 'g', rayon: 'Boucherie' },
      { nom: 'Épinards frais', quantite: 50, unite: 'g', rayon: 'Fruits & légumes' },
      { nom: "Huile d'olive", quantite: 5, unite: 'ml', rayon: 'Épicerie' },
    ],
    etapes: [
      "Battre les œufs avec les blancs d'œufs.",
      'Couper la pomme de terre cuite et le blanc de dinde en petits morceaux.',
      "Faire chauffer l'huile d'olive dans une poêle.",
      'Ajouter les épinards, la pomme de terre et le blanc de dinde.',
      "Verser les œufs battus et cuire à feu doux jusqu'à ce que la frittata soit prise.",
    ],
  },
];

module.exports = { RECIPES };
